### PR TITLE
Process multilanguage tags in relevant table cells

### PR DESCRIPTION
**Pull request by abias**
Hi Dan,

thank you for this helpful report plugin.
I would like to propose to process multilanguage tags in category, course and activity names to prevent cluttering of the table due to non-filtered names.

Cheers,
Alex

### CODE REVIEW

**Comment by danmarsden** [comment]
Hi Alex, 
Sorry - you sent this through during some refactoring by @tomdickman which has now been merged - it's now using some format_text calls but the mulitlanguage stuff might not be coming through properly yet - I'll try to take a look at this again next week before we push this updated code out to the plugins db.

**Comment by abias** [comment]
Hi Dan,

is there any news about this issue?

I have just dropped the latest github version into our production system, but I am still seeing multilang code in the Category column on /report/apocalypse/index.php.

Does it make sense that I re-investigate this issue and update the pull request or would it be easier that @tomdickman has a quick look?

Thanks,
Alex

**Comment by abias** [comment]
Hi @danmarsden , hi @tomdickman ,

I have had another look now and have seen that the format_text() calls which are been used in the plugin don't do anything with filters.

I have updated my pull request and would be happy if you could merge it.

Thanks,
Alex

**Comment by danmarsden** [comment]
Thanks Alex! - sorry I hadn't had a chance to look at this again - quite a bit of stuff in my backlog at the moment. Looks good to me - merged!

**Pull request merged**
